name: help_abode_worker_app_ver_2
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+38

environment:
  sdk: '>=3.2.3 <3.17.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  http: ^1.1.0
  flutter_svg: ^2.0.9
  pinput: ^3.0.1
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  change_app_package_name: ^1.1.0
  top_snackbar_flutter: ^3.1.0
  country_picker: ^2.0.22
  dropdown_button2: ^2.3.9
  #  image_picker: ^1.1.1
  shamsi_date: ^1.0.2
  flutter_time_picker_spinner: ^2.0.0
  time_picker_spinner_pop_up: ^1.2.1
  intl: ^0.18.1
  flutter_svg_provider: ^1.0.6
  image_picker: ^0.8.4+1
  camera: ^0.10.5+9
  #  flutter_inappwebview: ^5.8.0
  dotted_border: ^2.1.0
  #  url_strategy: ^0.2.0
  go_router: ^14.2.3
  provider: ^6.0.5
  connectivity_plus: ^6.1.3
  shared_preferences: ^2.2.2
  flutter_easyloading: ^3.0.5
  ensure_visible_when_focused: ^1.2.0
  flutter_expanded_tile: ^0.3.7
  fluttertoast: ^8.2.12
  flutter_html:
  flutter_launcher_icons: ^0.13.1
  flutter_holo_date_picker: ^1.1.3
  animated_bottom_navigation_bar: ^1.3.0
  contained_tab_bar_view: ^0.8.0
  rounded_loading_button_plus: ^3.0.1
  step_progress_indicator: ^1.0.2
  animations: ^2.0.10
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  #  mask_for_camera_view: ^2.0.4
  d_chart: ^2.6.7
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  loading_indicator: ^3.1.1
  flutter_sticky_header: ^0.7.0
  #  flutter_rating_bar: ^4.0.1
  flutter_rating_bar:
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  flutter_calendar_week: ^3.0.2
  animated_segmented_tab_control: ^1.2.1
  smooth_carousel_slider_widget: ^0.0.3
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^17.2.2
  app_settings: ^5.2.0
#  device_info_plus: ^11.1.0
  flutter_image_compress: ^2.3.0
  float_column: ^2.1.5
  url_launcher: ^6.3.0
  native_image_cropper: ^0.6.0
  web_socket_channel: ^3.0.1
  extended_masked_text: ^3.0.1
  image_cropper: ^8.0.2
  webview_flutter: ^4.10.0
  file_picker: ^8.0.6
  http_interceptor: ^2.0.0
  flutter_cached_pdfview: ^0.4.3
  fl_chart: ^0.69.0
  googleapis_auth: ^1.6.0
  table_calendar: ^3.0.9
  geocoding: ^3.0.0
  location: ^8.0.0
  syncfusion_flutter_datepicker: ^28.2.6
  flutter_polyline_points: ^2.1.0
#  mapbox_maps_flutter: ^2.6.1




  #  image_cropper: ^7.0.5
  #  overlay_support: ^2.1.0









  #  face_camera: ^0.0.8
  #  google_mlkit_face_detection:















dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos.png"
  min_sdk_android: 21

  # android min sdk min:16, default 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/svg/images (1)/
    - assets/png/
    - images/




  #icons_launcher:
  #  image_path: "assets/logos.png"
  #  platforms:
  #    android:
  #      enable: true
  #    ios:
  #      enable: true

  #    - assets/png/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages